"""
Django settings for Venter project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p!63vi=_4)o5h8k0ep4uy2e6ou^k$9wels#e&&x=^^!=$xa21o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'Prediction',
    'Login.apps.LoginConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Venter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'CategoryPrediction/../Login/templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Venter.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME' : os.path.join(BASE_DIR, 'db.sqlite3')
    }
}
# In the flexible environment, you connect to CloudSQL using a unix socket.
# Locally, you can use the CloudSQL proxy to proxy a localhost connection
# to the instance
# DATABASES['default']['HOST'] = '/cloudsql/ml-venter:us-central1:venter'
# if os.getenv('GAE_INSTANCE'):
#     pass
# else:
#     DATABASES['default']['HOST'] = '127.0.0.1'

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_ROOT = 'static'
STATIC_URL = '/static/'
#STATIC_URL = 'https://storage.googleapis.com/venterms/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "CategoryPrediction/../Login/static"),
]

LOGIN_REDIRECT_URL = 'home'

EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")

# Data folder stores the data of all users
MEDIA_ROOT = os.path.join(BASE_DIR, "MEDIA/")

# Maximum size of file uploaded by user
# 12534336 B = 12 MB
MAX_UPLOAD_SIZE = "12534336"

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000

SPEAKUP_CATEGORY_LIST = ['Delay in delivery', 'Wrong charges/Over charge', 'Consumer extremely frustated', 'Porting issues', 'Wrong/Faulty product',
                          'Payment Gateway failure', 'Internet issues', 'ATM related', 'Bad experience', 'Bad food',  'Staff Behaviour', 'Refund issues',
                          'Wrong charges', 'No Signal/Unable to use']


ICMC_CATEGORY_LIST = ['Drainage chokes and blockages', 'Overflowing drains or manholes',
                      'Replacement of missing/damaged manholes covers', 'Sunken manhole',
                      'Cleaning of septic tank', 'Repairs to pipe sewers/main sewers', 'Odour (foul smell) from drains',
                      'Bad patches/potholes on roads', 'Repairs/re-surfacing of roads/footpaths',
                      'Removal of rank regulation on roads', 'Reinstatement of trenches',
                      'Unauthorised digging of road', 'Providing name plates to the road', 'Street lighting', 'Signals',
                      'Speed breakers', 'Permission for tree cutting', 'Trimming of branches',
                      'Unauthorised Stalls on Roads', 'Fallen Tree on road', 'Bad Patches', 'Dangerous tree', 'Manhole',
                      'Flooding spot / Crosscut', 'Street furniture', 'Divider / Media',
                      'Unauthorised construction in slum', 'Unauthorised repairs/renovations in slum',
                      'Delay in transfer case',
                      'Unauthorised extension/construction', 'Unauthorised commercial activity', 'Lega',
                      'Issue of Birth / Death Certificate', 'Unauthorised Food Selling / Preparation',
                      'Unauthorized Flour Mill', 'Incorrect assessment of property', 'Non-availability of bills',
                      'Property Annexture, Transfer of Property, No Dues certificate, etc',
                      'Receipt against Online payment', 'Requirement to Assess the property',
                      'Searching the property details in absence of SACNo',
                      'Wrong billing name & address OR Wrong name of assessee',
                      'Wrong outstanding OR Payment related complaint', 'Delay in refund', 'Contact List of Wards',
                      'Unauthorised construction/development',
                      'Unauthorised alteration/renovation of building, flat, tenement, etc.',
                      'Permission for temporary monsoon shed',
                      'Regularisation of balcony enclosures',
                      'Repairs permission for tolerated/censured unauthorised structures',
                      'Granting authority u/s 499 of MMC Act for carrying out essential repairs',
                      'Heavy leakage from ceiling', 'Change of user - Res to Commercial', 'Establishment - Superio',
                      'Maintenance of municipal property, schools, dispensaries, maternity home, gardens',
                      'Maintenance of electric pumps in municipal colonies',
                      'Protection of municipal play grounds/gardens',
                      'Providing for monsoon to municipal property to avoid leakage',
                      'Providing/repairing doors, windows of P.S. Blocks',
                      'Proper electric supply to municipal properties', 'Major repairs to municipal property',
                      'Minor repairs to municipal property',
                      'Unauthorised stalls on roads, footpath or SWD drain',
                      'Unauthorised banners/advertisement/boards on roads/footpath',
                      'Unauthorised storage of explosives',
                      'Trade without License', 'Unauthorized workshop or Garage', 'Storage and sale of plastic bags',
                      'Mosquito nuisance', 'Rat nuisance', 'Fogging', 'Nuisance due to white ants',
                      'Nuisance due to cockroaches', 'Unauthorised/uncovered water storage tanks',
                      'Short supply of water', 'Choke in main drain', 'Drinking Water not available',
                      'Toilet not cleaned', 'Door/Window/staircase etc. found broken.', 'No electricity supply',
                      'Lamp,tubelight etc. to be replaced', 'Furniture found broken in the classes.',
                      'Found encroachment in the school premise', 'No Teacher', 'No warning/alarm system',
                      'Overflow of waste material', 'Pan/Gutka hawker near school premises',
                      'Bad Quality of material given to student', 'Pension / Family Pension Not Started',
                      'Current Month Pension / FP Not Received', 'Arrears Of Pension / FP Not Received',
                      'Gratuity Not Received', 'Commutation Of Pension Not Received',
                      'Arrears Of Pension Benefits Due To Rev.', '', 'NCPF Not Received',
                      'Leave Encashment Not Received',
                      'Cleaning of water entrance', 'Cleaning of open SWD', 'Flooding during monsoon',
                      'Pre-monsoon works halted', '"Providing damaged/missing gratings manhole covers over SWD\'s',
                      'Removal of silt from nalla/across culverts, etc.', 'Repair to damaged open SWD',
                      'Unauthorised Stalls and Huts on nallas', 'Raising of manhole (except in monsoon)',
                      'Garbage not lifted from co-authorised collection point', 'Garbage not lifted from house gully',
                      'Collection point not attended properly',
                      'Garbage not lifted from municipal market', 'Garbage lorry not reported for service',
                      'Garbage lorry not covered', 'Providing/removing/replacing dustbins',
                      'Removal of dead animals', 'Sweeping of road', 'Cleaning of P.S.C. block/channels',
                      'No attendance at public toilets', 'Removal of Debris', 'Silt to be lifted on road',
                      'Non attendant of Nuisance Detector', 'Lifting of Tree Cutting', 'Nuisance due to masala mills',
                      'Air pollution', 'Pollution due to chemical effluents',
                      'Unauthorised factory, workshop or garage', 'Pertaining to rent', 'Transfer of tenancy',
                      'Unauthorised construction on the Plot/Room', 'Unauthorised use of Room',
                      'Non-maintenance of Premises', 'Pending Transfer cases.',
                      'Unauthorised addition/alteration in the premises', 'Unauthorised materials/furniture found',
                      'Extension in the premises without permission', 'Slab fallen down.',
                      'Unauthorised shed on building in premises', 'Open beyond permissible hours',
                      'Running without licence',
                      'Non observance of Holidays', 'Not providing minimum wages', 'Shop open on weekly holiday',
                      'found staff working more than on muster', 'Employing children (below 14) in the org',
                      'Online Renewal Application', 'Municipal Land - Road / Footpath / Strom Water Drain',
                      'Municipal Plot', 'Municipal Colony / Slum', 'Hawkers',
                      'Private Land / Building / Society / Factories', 'Leaks in water lines', 'Burst water main',
                      'Contaminated water supply', 'Shortage of water supply',
                      'Unauthorised tapping of water connections', 'Unauthorised use of water-Change of User',
                      'Use of booster pump', 'Removal of water meters', 'Providing water by tankers',
                      'Water supply during non-supply hours', 'Leakage near meter',
                      'Overflow of overhead tank / suction tank', 'Non receipt of water bills', 'Establishment - Labou',
                      'Office Superintenden']

# ICMC_CATEGORY_LIST = [ u'गटार तुंबणे आणि साचणे', u'गटार किंवा मॅनहोल भरुन वाहणे', u'तुटलेले/हरवलेले मॅनहोल झाकण बसविणे', u'मॅनहोल खचणे',
# u'मॅनहोलमध्ये व्यक्ती पडणे', u'संडासाची टाकी साफ करणे', u'मलवाहिनी/मुख्य मलवाहिनी दुरुस्त करणे', u'गटारातून घाण वास येणे', u'रस्त्यावर खड्डे पडणे', u'रस्ता, फुटपाथ दुरुस्त/पुर्नबांधणी करणे',
# u'रस्त्यावरील खुरटी झाडे-झुडपे काढून टाकणे', u'चर बुजविणे', u'अनधिकृत रस्ता खोदणे', u'रस्त्यांना नांव फलक पुरविणे', u'रस्त्यावरील दिवा बत्ती', u'सिग्नलबाबत तक्रारी', u'गतिरोधक बसविणे', u'वृक्ष तोडण्यास परवानगीबाबत',
# u'वृक्ष छाटणीबाबत', u'रस्त्यावरील असलेली अनधिकृत दुकाने', u'रस्त्यावर झाड पडणे', u'गलिच्छ वस्त्यांमधील अनधिकृत बांधकामे', u'गलिच्छ वस्त्यांमधील अनधिकृत दुरूस्ती/नूतनीकरण', u'हस्तांतरित प्रकरणांना विलंब होणे', u'अनधिकृत वाढीव कामे/बांधकामे',
# u'अनधिकृत व्यवसाय करणे', u'जन्म/मृत्युचा दाखला देणे', u'अनधिकृत खाद्य पदार्थ बनविणे/ विकणे', u'अनधिकृत पिठाची गिरणी', u'मालमत्तेच्या करनिर्धारणाबाबत विवाद', u'मालमत्ता कराचे देयक प्राप्त झालेले नाही',
# u'मालमत्ता कराचे परिशिष्ट-अ, मालमत्तेचे हस्तांतरण तसेच थकित रक्कम शिल्लक नसल्याबाबतचे प्रमाणपत्र,इ', u'महाजालाद्वारे केलेल्या अधिदानाची पावती प्राप्त झाली नाही', u'मालमत्तेचे करनिर्धारण करण्याबाबत',
# u'15 अंकी मालमत्ता क्रमांक उपलब्ध नसल्यामुळे मालमत्तेचे तपशील प्राप्त होत नाही', u'देयकावर दर्शविण्यात आलेल्या नाव / पत्त्यात तफावत असल्यास अथवा करदात्याचे नाव अचूक नाही',
# u'चुकीची थकबाकी अथवा देयक संकलनाबाबत तक्रार', u'संकलनाच्या परताव्यासंबंधी विलंब', u'विभाग कार्यालये व संबंधीत अधिका-यांचे संपर्क', u'अनधिकृत बांधकामे', u'इमारतीचे, सदनिकेचे,वसाहतींमध्ये अनधिकृतरित्या अंतर्गत बदल करणे',
# u'पावसाळी शेडसाठी तात्पुरती परवानगी', u'बाल्कनी संदर्भातील कामे नियमित करणे', u'अनधिकृत असतानाही परवानगी दिलेल्या अनधिकृत बांधकामाची दुरूस्ती', u'म. न. पा. कायदयामधील कलम 499 अन्वये दुरूस्तीबाबत परवानगी देण्याबाबतचे अधिकार',
# u'छतामधुन मोठया प्रमाणात गळती', u'वापरात बदल घरगुती ते व्यापारी', u'महापालिकेच्या मालमत्तांचे, शाळांचे, दवाखान्यांचे, प्रसुतीगृहांचे व उद्यानांचे परिरक्षण करणे',
# u'पालिकेच्या वसाहितीतील विद्युत मोटारींचे परिरक्षण करणे', u'महापालिकेच्या मैदाने व उद्यानांचे संरक्षण करणे', u'महापालिकेच्या मालमत्तेमध्ये पावसाळी पाण्याची गळती थांबविण्यासाठी शेडची व्यवस्था करणे',
# u'सार्वजनिक शौचालयांना दरवाजे, खिडक्या पुरविणे/दुरूस्त करणे', u'महापालिकेच्या मालकीच्या जागांवर व्यवस्थित विद्युत पुरवठा करणे', u'महापालिकेच्या मालमत्तेची मोठी दुरूस्ती करणे',u'महापालिकेच्या मालमत्तेची किरकोळ दुरूस्ती करणे',
# u'रस्ता, फुटपाथ किंवा गटारांवर असलेली अनधिकृत दुकाने', u'रस्ता/पदपथावरील अनधिकृत फलक/जाहिराती', u'स्फोटकांचा अनधिकृत साठा', u'विनापरवाना व्यवसाय', u'अनधिकृत गॅरेज किंवा कार्यशाळा',
# u'प्लास्टिकच्या पिशव्यांच्या साठा करणे व विकणे', u'मच्छरांचा उपद्रव', u'उंदरांचा उपद्रव',u'धुम्र फवारणी',u'वाळवीचा उपद्रव',u'झुरळांचा उपद्रव',u'अनधिकृत/ न झाकलेला पाण्याचा साठा',u'पाण्याचा अपुरा पुरवठा',
# u'गटाराची मुख्य वाहिनी तुबंणे',u'पिण्याचे पाणी उपलब्ध न होणे',u'मुतारी स्वच्छ नसणे',u'दरवाजे/ खिडक्या/जिने तुटलेले असणे',u'विजेचा पुरवठा नसणे',u'बल्ब, टयुब लाईट इ. बदली करणे',u'वर्गातील लाकडी सामान तुटलेले आढळणे',
# u'शाळेच्या आवारात अतिक्रमण',u'शिक्षक नसणे',u'पूर्व सूचना देणारी पध्दत नसणे',u'कचरा तुडूंब भरून वाहणे',u'शाळेच्या आवाराजवळ पान/गुटखा फेरीवाले आढळणे',u'विद्यार्थ्यांना वाईट दर्जाचे सामान पुरविणे',u'निवृत्तीवेतन / कुटुंबनिवृत्तीवेतन सुरु करण्यात आलेले नाही',
# u'चालू महिन्याचे निवृतीवेतन / कुटुंब निवृत्तीवेतन मिळालेले नाही',u'निवृत्तीवेतनाची थकबाकी / कुटुंब निवृत्तीवेतनाची थकबाकी मिळालेली नाही',u'उपदान मिळालेले नाही',u'निवृत्तीवेतनाचे अंशराशीकरण मिळालेले नाही',u'वेतन सुधारणेमुळे निवृत्तीवेतनादी फायदे',u'थकबाकी येणे बाकी',
# u'अन-अंशदायी भविष्य निर्वाह निधी मिळालेला नाही',u'रजा रोखीची रक्कम मिळालेली नाही',u'पर्जन्य जलमुखाची स्वच्छता करणे',u'खुल्या पर्जन्य जलवाहिन्या साफ करणे',u'पावसाळयात पाणी तुंबणे',u'पावसाळापूर्व काम स्थगित होणे',u'पर्जन्य जलवाहिन्यांवरील/ गटारांवरील तुटलेली/गहाळ झालेली झाकणे पुरविणे',
# u'नाल्यातील गाळ काढणे', u'खुल्या पर्जन्य जलवाहिन्या दुरुस्त करणे',u'नाल्यावर असलेली अनधिकृत दुकाने आणि झोपडया', u'मॅनहोलची उंची वर उचलणे',u'एकत्रित केलेला कचरा नियोजित जागेवरुन न उचलणे',u'घरगल्ल्यांमधून कचरा न उचलणे',
# u'जमा केलेला कचरा व्यवस्थित न उचलणे',u'म.न.पा. मंडईतून कचरा न उचलणे',u'कचरागाडी सेवेसाठी न येणे',u'कचरागाडी झाकलेली नाही',u'कच-याचा डबा पुरविणे/काढणे/ बदलणे',u'मृत जनावरे उचलणे',u'रस्ता झाडणे',u'सार्वजनिक शौचालयांची स्वच्छता',
# u'सार्वजनिक स्वच्छता गृह दुर्लक्षित असणे',u'मातीचा ढिगारा उचलणे',u'रस्त्यावरील गाळ उचलणे',u'उपद्रव शोधक नसणे',u'कापलेल्या झाडांच्या फांदया उचलणे',u'मसाला गिरणीचा उपद्रव',u'हवा प्रदूषण',u'रासायनिक घटकांमुळे प्रदूषण',u'अनधिकृत कारखाने/कार्यशाळा/गॅरेज',
# u'भाडयाशी संबधित तक्रारी',u'भाडोञी जागेचे हस्तांतरण',u'प्लॉटवरील अनधिकृत बांधकाम',u'खेालीचा अनधिकृत वापर',u'जागेचे परिरक्षण न करणे',u'प्रलंबित हस्तांतरित प्रकरणे',u'अनधिकृत वाढविणे/ बदल',u'अनधिकृत सामान/ फर्निचर साठवुन ठेवणे',
# u'परवानगीशिवाय आवाराच्या जागेत विस्तार करणे',u'छज्जा (स्लॅब) पडणे',u'इमारतीच्या आवारात अनधिकृत शेड बांधणे',u'दुकाने परवानगी वेळे व्यतिरिक्त चालू ठेवणे',u'दुकाने विना परवाना चालू ठेवणे',u'सुट्टीचे पालन न करणे',u'किमान वेतन न देणे',
# u'आठवडा रजेच्या दिवशी दुकाने उघडी ठेवणे',u'हजेरी पटावर जास्त कर्मचारी आढळणे',u'14 वर्षाखालील मुलांना कामावर ठेवणे',u'महापालिकेच्या जमीन-रस्ता, पदपथ, पर्जन्य जल वाहिनीवरील अतिक्रमणे',u'महापालिकेचा भूखंड',u'महापालिकेच्या वसाहत/गलिच्छ वस्त्यांमधील अतिक्रमणे',
# u'फेरीवाले',u'खाजगी जमीन/इमारत/सोसायटी/कारखाने',u'जलवाहिनीमध्ये गळती',u'जलवाहिनी फुटणे',u'दुषित पाण्याचा पुरवठा',u'पाण्याचा तुटवडा',u'पाण्याची अनधिकृत नळ जोडणी',u'पाण्याचा अनधिकृत वापर',u'बुस्टर पंपाचा वापर',u'पाण्याचे मीटर काढून टाकणे',
# u'टँकरने पाणी पुरवठा करणे',u'पाणी पुरवठयावेळे व्यतिरिक्त पाणी पुरवठा करणे',u'जलमापका जवळ होणारी पाणी गळती',u'शोषण टाकी /गच्ची वरील टाकी भरून वाहते',u'जल देयके न मिळण्या बाबत']


ICMC_HEADERS = ['complaint_sub_category_iid', 'parent_cat_name', 'category_parent_iid', 'civic_agency_name',
                'complaint_title',
                'complaint_user_iid', 'user_iid', 'user_full_name', 'complaint_mobile_number', 'complaint_ward_iid',
                'ward_name', 'complaint_location', 'complaint_address_1', 'complaint_latitude', 'complaint_longitude',
                'complaint_created', 'latest_comp_satus_id', 'latest_comp_status_name', 'complaint_description']

SPEAKUP_HEADERS = ['id', 'user_id', 'vendor_id', 'complaint_type', 'feedback_status', 'get_response', 'last_response',
                   'got_resolved', 'resolved_date', 'send_reminder', 'text', 'phone', 'alt_phone', 'email',
                   'alt_email', 'city', 'state', 'image', 'voice', 'at_time', 'reference_id', 'contacted_date', 'status', 'updated_at',
                   'created_at', 'category_one', 'category', 'category_two']
